use_frameworks!

platform :ios, '9.0'

target 'PPBusinessComponent_Example' do
  pod 'PPBusinessComponent', :path => '../'

  target 'PPBusinessComponent_Tests' do
    inherit! :search_paths

    
  end
end
